version: '3.8'
services:
  postgres-song-service:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=song-service-db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - 5432:5432

  song-service:
    build:
      context: Song-Service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-song-service/song-service-db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    image: 'song-service'
    ports:
      - 8081:8081
    depends_on:
      - postgres-song-service

  postgres-resource-service:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=resource-service-db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - 5433:5432

  resource-service:
    build:
      context: Resource-Service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-resource-service/resource-service-db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    image: 'resource-service'
    ports:
      - 8080:8080
    depends_on:
      - postgres-resource-service